modLoader="javafml"
loaderVersion="[48,)"
license="All Rights Reserved"
issueTrackerURL="https://marco/restApi/issues"

[[mods]]

modId="restapi"
version="${version}"
displayName="restApi"
logoFile="icon.png"
description='''

'''

[[dependencies.restapi]]
   modId="forge"
   mandatory=true
   versionRange="[48,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.restapi]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.2,1.21)"
   ordering="NONE"
   side="BOTH"
