modLoader="javafml"
loaderVersion="[46,)"
license="All Rights Reserved"
issueTrackerURL="https://marco/restApi/issues"

[[mods]]

modId="restapi"
version="${version}"
displayName="restApi"
logoFile="icon.png"
description='''

'''

[[dependencies.restapi]]
   modId="forge"
   mandatory=true
   versionRange="[46,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.restapi]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20]"
   ordering="NONE"
   side="BOTH"

[[dependencies.restapi]]
   modId="architectury"
   mandatory=true
   versionRange="[7.1.86)"
   ordering="NONE"
   side="BOTH"
