modLoader="javafml"
loaderVersion="[44,)"
license="All Rights Reserved"
issueTrackerURL="https://marco/restApi/issues"

[[mods]]

modId="restapi"
version="${version}"
displayName="restApi"
logoFile="icon.png"
description='''

'''

[[dependencies.restapi]]
   modId="forge"
   mandatory=true
   versionRange="[44,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.restapi]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.3,1.19.4)"
   ordering="NONE"
   side="BOTH"
