modLoader="javafml"
loaderVersion="[${forge_mayor_version},)"
license="${license}"
issueTrackerURL="https://marco/restApi/issues"

[[mods]]

modId="restapi"
version="${version}"
displayName="${name}"
logoFile="icon.png"
description="${description}"
authors = "${author}"

[[dependencies.restapi]]
   modId="forge"
   mandatory=true
   versionRange="[${forge_mayor_version},)"
   ordering="NONE"
   side="BOTH"

[[dependencies.restapi]]
   modId="minecraft"
   mandatory=true
   versionRange="[${minecraft_version}]"
   ordering="NONE"
   side="BOTH"

[[dependencies.restapi]]
   modId="architectury"
   mandatory=true
   versionRange="[${architectury_version},)"
   ordering="NONE"
   side="BOTH"
