modLoader="javafml" #mandatory

loaderVersion="[48,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"

issueTrackerURL="https://marco/restApi/issues"

[[mods]] #mandatory

modId="restapi" #mandatory

version="${version}" #mandatory

displayName="restApi" #mandatory

logoFile="icon.png" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.restapi]] #optional
   # the modid of the dependency
   modId="forge" #mandatory
   # Does this dependency have to exist - if not, ordering below must be specified
   mandatory=true #mandatory
   # The version range of the dependency
   versionRange="[48,)" #mandatory
   # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
   ordering="NONE"
   # Side this dependency is applied on - BOTH, CLIENT or SERVER
   side="BOTH"
# Here's another dependency
[[dependencies.restapi]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="[1.20.2,1.21)"
   ordering="NONE"
   side="BOTH"
