modLoader="javafml"
loaderVersion="[${forge_mayor_version},)"
license="${license}"

[[mods]]

modId="${id}"
version="${version}"
displayName="${name}"
logoFile="icon.png"
description="${description}"
authors = "${author}"

[[dependencies.${id}]]
   modId="forge"
   mandatory=true
   versionRange="[${forge_mayor_version},)"
   ordering="NONE"
   side="BOTH"

[[dependencies.${id}]]
   modId="minecraft"
   mandatory=true
   versionRange="[${minecraft_version}]"
   ordering="NONE"
   side="BOTH"

[[dependencies.${id}]]
   modId="architectury"
   mandatory=true
   versionRange="[${architectury_version},)"
   ordering="NONE"
   side="BOTH"
