modLoader = "javafml"
loaderVersion = "*"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = "${description}"
logoFile = "icon.png"

[[dependencies.${id}]]
    modId = "neoforge"
    mandatory = true
    versionRange = "[${neoforge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_version}]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${id}]]
    modId = "architectury"
    mandatory = true
    versionRange = "[${architectury_version},)"
    ordering = "AFTER"
    side = "BOTH"